packages:
  - 'apps/*'
  - 'libs/*'
  - 'libs/shared/*'
  - 'packages/*'

onlyBuiltDependencies:
  - '@firebase/util'
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - bcrypt
  - canvas
  - esbuild
  - less
  - msgpackr-extract
  - nx
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
