export const API_ROUTES = {
  AUTH: {
    REGISTER:        '/auth/register',
    LOGIN:           '/auth/login',
    LOGOUT:          '/auth/logout',
    REFRESH:         '/auth/refresh',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD:  '/auth/reset-password',
    GOOGLE:          '/auth/google',
    GOOGLE_CALLBACK: '/auth/google/callback',
    VERIFY_EMAIL:    '/auth/verify-email',
  },
  USERS: {
    ME:              '/users/me',
    AVATAR:          '/users/me/avatar',
    PASSWORD:        '/users/me/password',
    ADDRESSES:       '/users/me/addresses',
    ADDRESS:         (id: string) => `/users/me/addresses/${id}`,
    WISHLIST:        '/users/me/wishlist',
    WISHLIST_ITEM:   (productId: string) => `/users/me/wishlist/${productId}`,
  },
  PRODUCTS: {
    LIST:            '/products',
    DETAIL:          (slug: string) => `/products/${slug}`,
    REVIEWS:         (slug: string) => `/products/${slug}/reviews`,
    REVIEW_SUMMARY:  (slug: string) => `/products/${slug}/reviews/summary`,
    RELATED:         (slug: string) => `/products/${slug}/related`,
  },
  CATALOG: {
    CATEGORIES:      '/catalog/categories',
    CATEGORY:        (slug: string) => `/catalog/categories/${slug}`,
    COLLECTIONS:     '/catalog/collections',
    COLLECTION:      (slug: string) => `/catalog/collections/${slug}`,
    TAGS:            '/catalog/tags',
  },
  CART: {
    GET:             '/cart',
    ADD:             '/cart/items',
    UPDATE_ITEM:     (itemId: string) => `/cart/items/${itemId}`,
    REMOVE_ITEM:     (itemId: string) => `/cart/items/${itemId}`,
    CLEAR:           '/cart/clear',
    MERGE:           '/cart/merge',
  },
  ORDERS: {
    LIST:            '/orders',
    DETAIL:          (orderNumber: string) => `/orders/${orderNumber}`,
    CREATE:          '/orders',
    CANCEL:          (orderNumber: string) => `/orders/${orderNumber}/cancel`,
  },
  PAYMENTS: {
    INTENT:          '/payments/intent',
    CONFIRM:         '/payments/confirm',
    GIFT_CARD_APPLY: '/payments/gift-card/apply',
    GIFT_CARD_BALANCE: '/payments/gift-card/balance',
    WEBHOOK:         '/payments/webhook',
  },
  PROMOTIONS: {
    VALIDATE:        '/promotions/validate',
  },
  SHIPPING: {
    CALCULATE:       '/shipping/calculate',
    METHODS:         '/shipping/methods',
  },
  CUSTOMIZATION: {
    UPLOAD:           '/customization/upload-image',
    REMOVE_BG:        '/customization/remove-background',
    APPLY_ART_STYLE:  '/customization/apply-art-style',
    JOB_STATUS:       (jobId: string) => `/customization/jobs/${jobId}`,
    PREVIEW:          '/customization/generate-preview',
    DRAFT:            '/customization/save-draft',
    LAST:             (productId: string) => `/customization/last/${productId}`,
    TEMPLATE:         (templateId: string) => `/customization/templates/${templateId}`,
  },
  REVIEWS: {
    UPLOAD_IMAGES:   (reviewId: string) => `/reviews/${reviewId}/images`,
    MY_REVIEWS:      '/reviews/me',
  },
  SEARCH: {
    QUERY:           '/search',
    SUGGESTIONS:     '/search/suggestions',
  },
  ADMIN: {
    DASHBOARD_KPIS:       '/admin/dashboard/kpis',
    DASHBOARD_REVENUE:    '/admin/dashboard/revenue',
    DASHBOARD_BY_STATUS:  '/admin/dashboard/orders-by-status',
    DASHBOARD_TOP:        '/admin/dashboard/top-products',
    PENDING_REVIEWS:      '/admin/dashboard/pending-reviews',
    ORDERS:               '/admin/orders',
    ORDER:                (id: string) => `/admin/orders/${id}`,
    USERS:                '/admin/users',
    USER:                 (id: string) => `/admin/users/${id}`,
    PRODUCTS:             '/admin/products',
    PRODUCT:              (id: string) => `/admin/products/${id}`,
    PROMOTIONS:           '/admin/promotions',
    PROMOTION:            (id: string) => `/admin/promotions/${id}`,
    SHIPPING_ZONES:       '/admin/shipping/zones',
    SHIPPING_ZONE:        (id: string) => `/admin/shipping/zones/${id}`,
    SHIPPING_METHODS:     (zoneId: string) => `/admin/shipping/zones/${zoneId}/methods`,
    SHIPPING_METHOD:      (id: string) => `/admin/shipping/methods/${id}`,
    REVIEWS:              '/admin/reviews',
    REVIEW_APPROVE:       (id: string) => `/admin/reviews/${id}/approve`,
    REVIEW_HIDE:          (id: string) => `/admin/reviews/${id}/hide`,
    REVIEW_REPLY:         (id: string) => `/admin/reviews/${id}/reply`,
  },
} as const;
