export const COUNTRIES: { code: string; name: string; flag: string }[] = [
  { code: 'US', name: 'United States',  flag: '🇺🇸' },
  { code: 'CA', name: 'Canada',         flag: '🇨🇦' },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧' },
  { code: 'AU', name: 'Australia',      flag: '🇦🇺' },
  { code: 'NZ', name: 'New Zealand',    flag: '🇳🇿' },
  { code: 'DE', name: 'Germany',        flag: '🇩🇪' },
  { code: 'FR', name: 'France',         flag: '🇫🇷' },
  { code: 'IT', name: 'Italy',          flag: '🇮🇹' },
  { code: 'ES', name: 'Spain',          flag: '🇪🇸' },
  { code: 'NL', name: 'Netherlands',    flag: '🇳🇱' },
  { code: 'SE', name: 'Sweden',         flag: '🇸🇪' },
  { code: 'NO', name: 'Norway',         flag: '🇳🇴' },
  { code: 'DK', name: 'Denmark',        flag: '🇩🇰' },
  { code: 'CH', name: 'Switzerland',    flag: '🇨🇭' },
  { code: 'AT', name: 'Austria',        flag: '🇦🇹' },
  { code: 'BE', name: 'Belgium',        flag: '🇧🇪' },
  { code: 'PL', name: 'Poland',         flag: '🇵🇱' },
  { code: 'JP', name: 'Japan',          flag: '🇯🇵' },
  { code: 'KR', name: 'South Korea',    flag: '🇰🇷' },
  { code: 'SG', name: 'Singapore',      flag: '🇸🇬' },
  { code: 'HK', name: 'Hong Kong',      flag: '🇭🇰' },
  { code: 'TW', name: 'Taiwan',         flag: '🇹🇼' },
  { code: 'MY', name: 'Malaysia',       flag: '🇲🇾' },
  { code: 'TH', name: 'Thailand',       flag: '🇹🇭' },
  { code: 'PH', name: 'Philippines',    flag: '🇵🇭' },
  { code: 'VN', name: 'Vietnam',        flag: '🇻🇳' },
  { code: 'IN', name: 'India',          flag: '🇮🇳' },
  { code: 'AE', name: 'UAE',            flag: '🇦🇪' },
  { code: 'SA', name: 'Saudi Arabia',   flag: '🇸🇦' },
  { code: 'BR', name: 'Brazil',         flag: '🇧🇷' },
  { code: 'MX', name: 'Mexico',         flag: '🇲🇽' },
  { code: 'ZA', name: 'South Africa',   flag: '🇿🇦' },
];
